general:
  collectTelemetryData: false
  verbose: true
steps:
  gctsDeploy:
    host: 'http://54.227.214.122:8000'
    client: '500'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-zgcts_wrgcts_prep'
  gctsExecuteABAPUnitTests:
    host: 'http://54.227.214.122:8000'
    client: '500'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-zgcts_wrgcts_prep'
  gctsRollback:
    host: 'http://54.227.214.122:8000'
    client: '500'
    abapCredentialsId: 'gCTS_target'
    repository: 'dreamer-nv-zgcts_wrgcts_prep'
  abapEnvironmentRunATCCheck:
    abapCredentialsId: 'gCTS_target'
    host: 'gprd.sapds.ru:44300'
    atcConfig: 'atcconfig.yml'
